Feat: Initial code import from releng-reusable-workflows
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -3,15 +3,16 @@
 # SPDX-FileCopyrightText: 2025 The Linux Foundation
 
 # Action test/validation workflow
-name: "Test GitHub Action 🧪"
+name: 'Test GitHub Action 🧪'
 
 # yamllint disable-line rule:truthy
 on:
   workflow_dispatch:
   push:
-    branches: ["main"]
+    branches: ['main']
   pull_request:
-    branches: ["main"]
+    branches: ['main']
+
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -22,48 +23,50 @@ permissions: {}
 jobs:
   ### Test the GitHub Action in this Repository ###
   tests:
-    name: "Test local GitHub Action"
-    runs-on: ubuntu-24.04
+    name: 'Test local GitHub Action'
+    runs-on: 'ubuntu-latest'
     permissions:
       contents: read
     timeout-minutes: 10 # Increase this timeout value as needed
     steps:
-      - name: "Checkout repository"
+      - name: 'Checkout repository'
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      # Perform setup prior to running test(s)
-      - name: "Testing setup step"
-        shell: bash
+      - name: 'Test vars/secrets are available'
         run: |
-          # Testing setup step
-          echo "Testing setup step"
-          echo "Testing setup step/summary output" >> "$GITHUB_STEP_SUMMARY"
+          # Test vars/secrets are available
+          if [ -n "${{ vars.NEXUS_IQ_SERVER }}" ]; then
+            echo "NEXUS_IQ_SERVER: ${{ vars.NEXUS_IQ_SERVER }}"
+          else
+            echo "NEXUS_IQ_SERVER is not available"
+            error='true'
+          fi
+          if [ -n "${{ vars.NEXUS_IQ_USERNAME }}" ]; then
+            echo "NEXUS_IQ_USERNAME: ${{ vars.NEXUS_IQ_USERNAME }}"
+          else
+            echo "NEXUS_IQ_USERNAME is not available"
+            error='true'
+          fi
+          if [ -n "${{ secrets.NEXUS_IQ_PASSWORD }}" ]; then
+            echo "NEXUS_IQ_PASSWORD is set"
+          else
+            echo "NEXUS_IQ_PASSWORD is not available"
+            error='true'
+          fi
+          # Abort if variables/secrets are not available
+          if [ "$error" = 'true' ]; then
+            echo "Error: mandatory variables/secrets are not configured ❌"
+            exit 1
+          else
+            echo "All mandatory variables/secrets are available ✅"
+          fi
 
       - name: "Running local action: ${{ github.repository }}"
         uses: ./
         with:
-          input: "test input 💬"
-
-      - name: "Validated local action: ${{ github.repository }}"
-        shell: bash
-        run: |
-          # Local action validation
-          echo "Validated local action: ${{ github.repository }}"
-          echo "Validation step summary output" >> "$GITHUB_STEP_SUMMARY"
-
-      # yamllint disable-line rule:line-length
-      - name: "Running local action: ${{ github.repository }} [Override Failure]"
-        uses: ./
-        id: failure
-        continue-on-error: true
-        with:
-          invalid_input: "Some garbage"
-
-      # Failure testing is also important
-      - name: "Error if step above did NOT fail"
-        if: steps.failure.outcome == 'success'
-        shell: bash
-        run: |
-          # Error if step above did NOT fail
-          echo "Error: previous test step did NOT fail ❌"
-          exit 1
+          no_checkout: 'true'
+          nexus_iq_server: "${{ vars.NEXUS_IQ_SERVER }}"
+          nexus_iq_username: "${{ vars.NEXUS_IQ_USERNAME }}"
+          nexus_iq_password: "${{ secrets.NEXUS_IQ_PASSWORD }}"
+          application_id: 'lfreleng-actions-sonatype-lifecycle-scan-action'
+          debug: 'true'
